openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: http://localhost:7001
paths:
  /v1/test:
    post:
      summary: Test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TestComponent"
      responses:
        "200":
          description: Testing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestComponent"
components:
  schemas:
    TestComponent:
      type: object
      properties:
        testprop1:
          type: integer
        testprop2:
          type: string
          description: Desc